services:
  bot:
    build: .
    container_name: megachinese-bot
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      RUST_LOG: info
    restart: unless-stopped
    network_mode: host
